repository_type: pipeline
lint:
  files_exist:
  - CODE_OF_CONDUCT.md
  - assets/nf-core-rewarewaannotation_logo_light.png
  - docs/images/nf-core-rewarewaannotation_logo_light.png
  - docs/images/nf-core-rewarewaannotation_logo_dark.png
  - .github/ISSUE_TEMPLATE/config.yml
  - .github/workflows/awstest.yml
  - .github/workflows/awsfulltest.yml
  - docs/output.md
  - lib/Utils.groovy
  - lib/WorkflowMain.groovy
  - lib/NfcoreTemplate.groovy
  - lib/WorkflowRewarewaannotation.groovy
  - lib/nfcore_external_java_deps.jar
  - pipeline_template.yml
  nextflow_config:
  - manifest.name
  - manifest.homePage
  multiqc_config:
  - report_comment
  files_unchanged:
  - .github/CONTRIBUTING.md
  - .github/ISSUE_TEMPLATE/bug_report.yml
  - .github/PULL_REQUEST_TEMPLATE.md
  - .github/workflows/branch.yml
  - .github/workflows/linting_comment.yml
  - .github/workflows/linting.yml
  - assets/email_template.html
  - docs/README.md
  - pyproject.toml
